module FeedSetting
  DAY_COMPARE = 30
  UPDATED_POLL = 2
  VOTED = 2
  NOT_YET_VOTE = 4
  CREATED_RECENT = 10

  PUBLIC_FEED = 5
  GROUP_FEED = 4
  FRIEND_FOLLOWING_FEED = 3

  RANGE_TIME_COMPARE = 300
end