json.member_id member.id
json.name member.sentai_name
json.username member.username
json.email member.email
json.type member.member_type_text
json.description member.get_description
json.key_color member.get_key_color
json.avatar member.get_avatar
json.cover member.get_cover_image
json.sync_facebook member.sync_facebook
json.anonymous member.anonymous