json.member_id member.id
json.name member.get_name
json.public_id member.get_public_id
json.email member.get_email
json.type member.member_type_text
json.description member.get_description
json.avatar member.get_avatar
json.cover member.get_cover_image
json.cover_preset member.get_cover_preset