json.id group.id
json.name group.name
json.photo group.get_photo_group
json.member_count group.get_member_active.count
json.poll_count group.poll_count
json.description group.get_description
json.public group.public
json.leave_group group.leave_group
json.created_at group.created_at.to_i