---
development:
  cloud_name: code-app
  api_key: '543692587982572'
  api_secret: lHBP7L-JOLt-sRXDLMWlI6doib8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: code-app
  api_key: '543692587982572'
  api_secret: lHBP7L-JOLt-sRXDLMWlI6doib8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: code-app
  api_key: '543692587982572'
  api_secret: lHBP7L-JOLt-sRXDLMWlI6doib8
  enhance_image_tag: true
  static_image_support: false
