development:
  cloud_name: dskrbthch
  api_key: '951459966873843'
  api_secret: BDRG0rXlHCH7Ndl8Pw68OxqSXMA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dskrbthch
  api_key: '951459966873843'
  api_secret: BDRG0rXlHCH7Ndl8Pw68OxqSXMA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dskrbthch
  api_key: '951459966873843'
  api_secret: BDRG0rXlHCH7Ndl8Pw68OxqSXMA
  enhance_image_tag: true
  static_image_support: false
