defaults: &defaults
  cool:
    saweet: nested settings
  neat_setting: 24
  awesome_setting: <%= 123 %>

development:
  <<: *defaults
  neat_setting: 800
  nut: nuttapon

test:
  <<: *defaults

production:
  <<: *defaults