json.id group.id
json.name group.name
json.photo group.get_photo_group
json.member_count group.get_all_member_count
json.poll_count group.get_all_poll_count
json.description group.get_description
json.public group.public
json.created_at group.created_at.to_i
json.leave_group group.leave_group
json.cover group.get_cover_group